# Generated by Django 3.1.1 on 2020-09-28 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=245, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('ruc', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('idunidadmedida', models.IntegerField(db_column='idunidadMedida', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'unidad_de_medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('codigobarra', models.CharField(db_column='codigoBarra', max_length=250, unique=True)),
                ('preciocompra', models.DecimalField(db_column='precioCompra', decimal_places=0, max_digits=10)),
                ('precioventa', models.DecimalField(db_column='PrecioVenta', decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=45)),
                ('categoria_idcategoria', models.ForeignKey(db_column='categoria_idcategoria', on_delete=django.db.models.deletion.DO_NOTHING, to='ferreteria.categoria')),
                ('proveedor_idproveedor', models.ForeignKey(db_column='proveedor_idproveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='ferreteria.proveedor')),
            ],
            options={
                'db_table': 'producto',
                'unique_together': {('idproducto', 'categoria_idcategoria', 'proveedor_idproveedor')},
            },
        ),
        migrations.CreateModel(
            name='ProductoPorUnidadDeMedida',
            fields=[
                ('producto_idproducto', models.OneToOneField(db_column='producto_idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ferreteria.producto')),
                ('precioventa', models.DecimalField(blank=True, db_column='precioVenta', decimal_places=0, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('unidad_de_medida_idunidadmedida', models.ForeignKey(db_column='unidad_de_medida_idunidadMedida', on_delete=django.db.models.deletion.DO_NOTHING, to='ferreteria.unidaddemedida')),
            ],
            options={
                'db_table': 'producto_por_unidad_de_medida',
                'unique_together': {('producto_idproducto', 'unidad_de_medida_idunidadmedida')},
            },
        ),
    ]
